[project]
name = "behavioral-finance-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.behavioral-finance-token]
path = "contracts/behavioral-finance-token.clar"
depends_on = ["sip-010-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
depends_on = []
